description: iib_DomainNet

target:
  service: amlk8s
  name: itpeusp40cl
  vc: resrchvc


environment:
  image: yezhenwang/yezhens_workstation:v1.6
  setup:
    - source /opt/conda/bin/activate
    - pip install h5py
    - pip install tqdm
    - pip install wandb
    - pip install openpyxl
    - pip install urllib3
    - pip install wilds
# environment:
#   image: pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: /home/v-boli4/teamdrive/users/drluodian/DomainBed

data:
  remote_dir: data

jobs:
  - name: domainbed_dn_0
    sku: G1
    sku_count: 1
    aml_mpirun:
      process_count_per_node: 1
      communicator: "OpenMpi"
    command:
      - python -m domainbed.scripts.train --data_dir=$$PT_DATA_DIR --algorithm IIB --dataset DomainNet --hparams_path ./amlt_yamls/office_home.json --test_envs 0
  - name: domainbed_dn_1
    sku: G1
    sku_count: 1
    aml_mpirun:
      process_count_per_node: 1
      communicator: "OpenMpi"
    command:
      - python -m domainbed.scripts.train --data_dir=$$PT_DATA_DIR --algorithm IIB --dataset DomainNet --hparams_path ./amlt_yamls/office_home.json --test_envs 1
  - name: domainbed_dn_2
    sku: G1
    sku_count: 1
    aml_mpirun:
      process_count_per_node: 1
      communicator: "OpenMpi"
    command:
      - python -m domainbed.scripts.train --data_dir=$$PT_DATA_DIR --algorithm IIB --dataset DomainNet --hparams_path ./amlt_yamls/office_home.json --test_envs 2
  - name: domainbed_dn_3
    sku: G1
    sku_count: 1
    aml_mpirun:
      process_count_per_node: 1
      communicator: "OpenMpi"
    command:
      - python -m domainbed.scripts.train --data_dir=$$PT_DATA_DIR --algorithm IIB --dataset DomainNet --hparams_path ./amlt_yamls/office_home.json --test_envs 3
  - name: domainbed_dn_4
    sku: G1
    sku_count: 1
    aml_mpirun:
      process_count_per_node: 1
      communicator: "OpenMpi"
    command:
      - python -m domainbed.scripts.train --data_dir=$$PT_DATA_DIR --algorithm IIB --dataset DomainNet --hparams_path ./amlt_yamls/office_home.json --test_envs 4
  - name: domainbed_dn_5
    sku: G1
    sku_count: 1
    aml_mpirun:
      process_count_per_node: 1
      communicator: "OpenMpi"
    command:
      - python -m domainbed.scripts.train --data_dir=$$PT_DATA_DIR --algorithm IIB --dataset DomainNet --hparams_path ./amlt_yamls/office_home.json --test_envs 5