description: IIBv5

target:
  service: amlk8s
  name: itpscusv100cl
  vc: resrchvc


environment:
  image: yezhenwang/yezhens_workstation:v1.7
  setup:
    - source /opt/conda/bin/activate
    - pip install h5py
    - pip install tqdm
    - pip install wandb
    - pip install openpyxl
    - pip install urllib3
    - pip install wilds
    - wandb login abc1859572354a66fc85b2ad1d1009add929cbfa
# environment:
#   image: pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: /home/v-boli4/teamdrive/users/drluodian/DomainBed

data:
  remote_dir: data

jobs:
  - name: domainbed_IIBv4_VLCS_1e-4_1_True
    sku: G8
    sku_count: 1
    aml_mpirun:
      process_count_per_node: 1
      communicator: "OpenMpi"
    command:
      - python -m domainbed.scripts.sweep launch --data_dir=$$PT_DATA_DIR --algorithm IIB --datasets VLCS --output_dir $$AMLT_OUTPUT_DIR --command_launcher multi_gpu --lambda_beta 1e-4 --lambda_inv_risks 1 --enable_bn True --skip_confirmation
  - name: domainbed_IIBv4_VLCS_1e-4_10_True
    sku: G8
    sku_count: 1
    aml_mpirun:
      process_count_per_node: 1
      communicator: "OpenMpi"
    command:
      - python -m domainbed.scripts.sweep launch --data_dir=$$PT_DATA_DIR --algorithm IIB --datasets VLCS --output_dir $$AMLT_OUTPUT_DIR --command_launcher multi_gpu --lambda_beta 1e-4 --lambda_inv_risks 10 --enable_bn True --skip_confirmation
  - name: domainbed_IIBv4_PACS_1e-4_1_True
    sku: G8
    sku_count: 1
    aml_mpirun:
      process_count_per_node: 1
      communicator: "OpenMpi"
    command:
      - python -m domainbed.scripts.sweep launch --data_dir=$$PT_DATA_DIR --algorithm IIB --datasets PACS --output_dir $$AMLT_OUTPUT_DIR --command_launcher multi_gpu --lambda_beta 1e-4 --lambda_inv_risks 1 --enable_bn True --skip_confirmation
  - name: domainbed_IIBv4_PACS_1e-4_10_True
    sku: G8
    sku_count: 1
    aml_mpirun:
      process_count_per_node: 1
      communicator: "OpenMpi"
    command:
      - python -m domainbed.scripts.sweep launch --data_dir=$$PT_DATA_DIR --algorithm IIB --datasets PACS --output_dir $$AMLT_OUTPUT_DIR --command_launcher multi_gpu --lambda_beta 1e-4 --lambda_inv_risks 10 --enable_bn True --skip_confirmation
  - name: domainbed_IIBv4_OfficeHome_1e-4_1_True
    sku: G8
    sku_count: 1
    aml_mpirun:
      process_count_per_node: 1
      communicator: "OpenMpi"
    command:
      - python -m domainbed.scripts.sweep launch --data_dir=$$PT_DATA_DIR --algorithm IIB --datasets OfficeHome --output_dir $$AMLT_OUTPUT_DIR --command_launcher multi_gpu --lambda_beta 1e-4 --lambda_inv_risks 1 --enable_bn True --skip_confirmation
  - name: domainbed_IIBv4_OfficeHome_1e-4_10_True
    sku: G8
    sku_count: 1
    aml_mpirun:
      process_count_per_node: 1
      communicator: "OpenMpi"
    command:
      - python -m domainbed.scripts.sweep launch --data_dir=$$PT_DATA_DIR --algorithm IIB --datasets OfficeHome --output_dir $$AMLT_OUTPUT_DIR --command_launcher multi_gpu --lambda_beta 1e-4 --lambda_inv_risks 10 --enable_bn True --skip_confirmation
  - name: domainbed_IIBv4_TerraIncognita_1e-4_1_True
    sku: G8
    sku_count: 1
    aml_mpirun:
      process_count_per_node: 1
      communicator: "OpenMpi"
    command:
      - python -m domainbed.scripts.sweep launch --data_dir=$$PT_DATA_DIR --algorithm IIB --datasets TerraIncognita --output_dir $$AMLT_OUTPUT_DIR --command_launcher multi_gpu --lambda_beta 1e-4 --lambda_inv_risks 1 --enable_bn True --skip_confirmation
  - name: domainbed_IIBv4_TerraIncognita_1e-4_10_True
    sku: G8
    sku_count: 1
    aml_mpirun:
      process_count_per_node: 1
      communicator: "OpenMpi"
    command:
      - python -m domainbed.scripts.sweep launch --data_dir=$$PT_DATA_DIR --algorithm IIB --datasets TerraIncognita --output_dir $$AMLT_OUTPUT_DIR --command_launcher multi_gpu --lambda_beta 1e-4 --lambda_inv_risks 10 --enable_bn True --skip_confirmation